### ISSUE TITLE
Dinderie !

### ISSUE THREAD

**Issue by VigibotDev** [Retr0Kr0dy/malloc-bomb#2]
![tenor](https://github.com/Retr0Kr0dy/malloc-bomb/assets/4873680/283d22ef-dcea-434b-a8cd-e9097e8bdb05)

**Comment by Retr0Kr0dy** [comment]
![conceit](https://github.com/Retr0Kr0dy/malloc-bomb/assets/91196264/04836507-1bab-4d21-8140-dba211f384b0)
